/**
 * Password hashing for the Orders admin.
 *
 * PBKDF2-SHA256 through WebCrypto, which exists identically in Node and on the
 * Cloudflare Worker — so the hash generated by scripts/admin-password.mjs is
 * verified by the same code that runs in production.
 *
 * The plaintext password is never stored anywhere: .env holds only the hash,
 * and the hash cannot be turned back into the password.
 *
 * Fields are separated by ":" and never "$", which is the conventional choice:
 * Vite runs dotenv-expand over .env, so a "$" in the value is read as a
 * variable reference and silently eaten. The hash then never matches and the
 * login fails with no clue why.
 */

/**
 * Cloudflare Workers refuses PBKDF2 above 100,000 iterations outright:
 *   NotSupportedError: Pbkdf2 failed: iteration counts above 100000 are not supported
 * It is a deliberate denial-of-service guard on their side, not a bug on ours.
 *
 * Node has no such cap, so 210,000 worked locally for weeks and then threw on
 * the very first real login attempt in production — an unhandled rejection, a
 * bare 500 and an empty body.
 *
 * 100,000 is therefore the ceiling, not a choice. It is below the 600,000 OWASP
 * asks of PBKDF2-SHA-256, and that gap is real: it is roughly six times cheaper
 * to attack a stolen hash. What carries the weight instead is everything around
 * it — one account rather than a user table, a long random password, a hash
 * that lives only in an encrypted environment variable, and a session that
 * expires. If the hash ever leaks, rotate the password; do not rely on the
 * iteration count to buy time it cannot buy.
 */
const MAX_WORKER_ITERATIONS = 100_000;
const ITERATIONS = MAX_WORKER_ITERATIONS;
const KEY_LENGTH = 32;

const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes));
const unb64 = (s: string) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

async function derive(password: string, salt: Uint8Array, iterations: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits"]
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations, hash: "SHA-256" },
    key,
    KEY_LENGTH * 8
  );
  return new Uint8Array(bits);
}

/** Produces the string that goes in ADMIN_PASSWORD_HASH. */
export async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const hash = await derive(password, salt, ITERATIONS);
  return `pbkdf2:${ITERATIONS}:${b64(salt)}:${b64(hash)}`;
}

/** Compares without leaking, through timing, how much of the hash matched. */
function constantTimeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const parts = (stored || "").split(":");
  if (parts.length !== 4 || parts[0] !== "pbkdf2") return false;

  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations < 1000) return false;
  /* A hash generated before this cap was known would make deriveBits THROW
     rather than return false, and an exception here is an empty 500 at the
     login screen with nothing to read. Refuse it as a mismatch and say why in
     the log, so the fix — regenerate the hash — is discoverable. */
  if (iterations > MAX_WORKER_ITERATIONS) {
    console.error(
      "[VP-ADMIN-HASH-TOO-STRONG] ADMIN_PASSWORD_HASH was generated with",
      iterations,
      "iterations. Cloudflare Workers refuses anything above",
      MAX_WORKER_ITERATIONS + ".",
      "Nobody can log in until it is regenerated: npm run admin:password -- \"<password>\""
    );
    return false;
  }

  let salt: Uint8Array;
  let expected: Uint8Array;
  try {
    salt = unb64(parts[2]);
    expected = unb64(parts[3]);
  } catch {
    return false;
  }

  const actual = await derive(password, salt, iterations);
  return constantTimeEqual(actual, expected);
}
