/**
 * Password hashing for the Orders admin.
 *
 * PBKDF2-SHA256 through WebCrypto, which exists identically in Node and on the
 * Cloudflare Worker — so the hash generated by scripts/admin-password.mjs is
 * verified by the same code that runs in production.
 *
 * The plaintext password is never stored anywhere: .env holds only the hash,
 * and the hash cannot be turned back into the password.
 *
 * Fields are separated by ":" and never "$", which is the conventional choice:
 * Vite runs dotenv-expand over .env, so a "$" in the value is read as a
 * variable reference and silently eaten. The hash then never matches and the
 * login fails with no clue why.
 */

const ITERATIONS = 210_000;
const KEY_LENGTH = 32;

const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes));
const unb64 = (s: string) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

async function derive(password: string, salt: Uint8Array, iterations: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits"]
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations, hash: "SHA-256" },
    key,
    KEY_LENGTH * 8
  );
  return new Uint8Array(bits);
}

/** Produces the string that goes in ADMIN_PASSWORD_HASH. */
export async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const hash = await derive(password, salt, ITERATIONS);
  return `pbkdf2:${ITERATIONS}:${b64(salt)}:${b64(hash)}`;
}

/** Compares without leaking, through timing, how much of the hash matched. */
function constantTimeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const parts = (stored || "").split(":");
  if (parts.length !== 4 || parts[0] !== "pbkdf2") return false;

  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations < 1000) return false;

  let salt: Uint8Array;
  let expected: Uint8Array;
  try {
    salt = unb64(parts[2]);
    expected = unb64(parts[3]);
  } catch {
    return false;
  }

  const actual = await derive(password, salt, iterations);
  return constantTimeEqual(actual, expected);
}
